version: "3.9"

services:
  amharicrag:
    build:
      context: .
      dockerfile: Dockerfile
    image: amharicrag:latest
    container_name: amharicrag_container
    depends_on:
      - qdrant
    ports:
      - "8071:8071"

  qdrant:
    image: qdrant/qdrant:v1.3.0
    container_name: qdrant
    ports:
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_API_KEY=

volumes:
  qdrant_data:
  # ollama_data:
